#!/bin/bash
home=$(eval echo ~$user)

for subj in 01 02 03 04 05 06 07 09 10 11 12 13 14 15 16 17 18 20 21 22 23 24 25 26
  do
  #mv ${home}/SAVED/RAW/${subj}/second/sub-${subj}_ses-second_run-01_sbref.nii.gz ${home}/REWOD/sub-${subj}/ses-second/anat/
  #mv ${home}/SAVED/RAW/${subj}/second/sub-${subj}_ses-second_run-01_sbref.json ${home}/REWOD/sub-${subj}/ses-second/anat/
  #mv ${home}/REWOD/sub-${subj}/ses-second/func/sub-02_ses-second_run-01_sbref.json ${home}/REWOD/sub-${subj}/ses-second/func/sub-02_ses-second_task-PIT_run-01_sbref.json
  #mv ${home}/REWOD/sub-${subj}/ses-second/func/sub-02_ses-second_run-01_sbref.nii.gz ${home}/REWOD/sub-${subj}/ses-second/func/sub-02_ses-second_task-PIT_run-01_sbref.nii.gz
  #mv ${home}/REWOD/sub-${subj}/ses-second/func/sub-${subj}_ses-second_run-01_sbref.nii.gz ${home}/REWOD/sub-${subj}/ses-second/func/sub-${subj}_ses-second_task-PIT_run-01_sbref.nii.gz
  #mv ${home}/REWOD/sub-${subj}/ses-second/func/sub-${subj}_ses-second_run-01_sbref.json ${home}/REWOD/sub-${subj}/ses-second/func/sub-${subj}_ses-second_task-PIT_run-01_sbref.json
  #cp ${home}/REWOD/sub-${subj}/ses-second/func/sub-${subj}_ses-second_task-PIT_run-01_sbref.nii.gz ${home}/REWOD/sub-${subj}/ses-second/func/sub-${subj}_ses-second_task-hedonic_run-01_sbref.nii.gz
  #cp ${home}/REWOD/sub-${subj}/ses-second/func/sub-${subj}_ses-second_task-PIT_run-01_sbref.json ${home}/REWOD/sub-${subj}/ses-second/func/sub-${subj}_ses-second_task-hedonic_run-01_sbref.json
  #mv ${home}/REWOD/sub-${subj}/ses-first/beh/sub-${subj}_ses-first_task-instrumental_learning_run-01_events.tsv ${home}/REWOD/sub-${subj}/ses-first/beh/sub-${subj}_ses-first_task-instrulearning_run-01_events.tsv
  #mv ${home}/REWOD/sub-${subj}/ses-first/beh/sub-${subj}_ses-first_task-pavlearning_run-01_events.tsv ${home}/REWOD/sub-${subj}/ses-first/beh/sub-${subj}_ses-first_task-pavconditioning_run-01_events.tsv
  #atom ${home}/REWOD/sub-${subj}/ses-second/fmap/sub-${subj}_ses-second_run-01_phasediff.json

  ##cp -r ${home}/SAVED/BEHAVIOR/DATA/RAW/BEHAVIORAL/CONDITIONING/${subj}/one/c* ${home}/REWOD/SOURCEDATA/${subj}/ses-first_task-pavconditioning/
  #cp -r ${home}/SAVED/BEHAVIOR/DATA/RAW/BEHAVIORAL/HEDONIC/${subj}/one/h* ${home}/REWOD/SOURCEDATA/${subj}/ses-first_task-hedonic/
  #cp -r ${home}/SAVED/BEHAVIOR/DATA/RAW/BEHAVIORAL/HEDONIC/${subj}/two/h* ${home}/REWOD/SOURCEDATA/${subj}/ses-second_task-hedonic/
  #cp -r ${home}/SAVED/BEHAVIOR/DATA/RAW/BEHAVIORAL/PIT/${subj}/two/P* ${home}/REWOD/SOURCEDATA/${subj}/ses-second_task-PIT/
  #cp -r ${home}/SAVED/BEHAVIOR/DATA/RAW/BEHAVIORAL ${subj}/* ${home}/REWOD/sub-${subj}/


  mkdir ${home}/REWOD/SOURCEDATA/behav/${subj}
  mv ${home}/REWOD/SOURCEDATA/brain/${subj}/ses* ${home}/REWOD/SOURCEDATA/behav/${subj}/
  #mv ${home}/REWOD/DERIVATIVES/PREPROC/sub-${subj}/ses-first/behav ${home}/REWOD/DERIVATIVES/PREPROC/sub-${subj}/ses-first/beh
  #mv ${home}/REWOD/DERIVATIVES/PREPROC/sub-${subj}/ses-first/beh/behav  ${home}/REWOD/sub-${subj}/ses-first/beh
  #mv ${home}/SAVED/RAW/${subj}/second/sub-${subj}_ses-second_run-01_fmap_magnitude.json ${home}/REWOD/sub-${subj}/ses-second/fmap/sub-${subj}_ses-second_run-01_magnitude.json
  #mv ${home}/SAVED/RAW/${subj}/second/sub-${subj}_ses-second_run-01_fmap_magnitude.nii.gz ${home}/REWOD/sub-${subj}/ses-second/fmap/sub-${subj}_ses-second_run-01_magnitude.nii.gz
  #mv ${home}/SAVED/RAW/${subj}/second/sub-${subj}_ses-second_run-01_fmap_phasediff.json ${home}/REWOD/sub-${subj}/ses-second/fmap/sub-${subj}_ses-second_run-01_phasediff.json
  #mv ${home}/SAVED/RAW/${subj}/second/sub-${subj}_ses-second_run-01_fmap_phasediff.nii.gz ${home}/REWOD/sub-${subj}/ses-second/fmap/sub-${subj}_ses-second_run-01_phasediff.nii.gz
done
